Remote unnessesary ternarys
FreeRTOS/coreMQTT pull request #211
Opened 2022-09-12 22:21 UTC by archigup

2022-09-12 22:32 UTC, AniruddhaKanhere requested changes
There are many places where we use a pattern: `if( xVariable == true )`. I prefer those over just using `if( xVariable )`.
The first one seems clearer to me. It might also help us catch bugs. Think of an extreme case when the bool variable was changed to a pointer. The new version would check for that pointer being NULL and compiler won't complain - in the older version, compiler would complain about it forcing us to fix it.

2022-09-12 22:32 UTC, AniruddhaKanhere commented on source/core_mqtt.c
> +        if( nextLevelExistsInTopicName && !nextLevelExistsinTopicFilter )
I would prefer the original to the modified version. The original seems more clear to me.

2022-09-12 22:32 UTC, AniruddhaKanhere commented on source/core_mqtt.c
> +        else if( nextLevelExistsInTopicName )
Here too. I would prefer the original.

2022-09-12 22:32 UTC, AniruddhaKanhere commented on source/core_mqtt.c
> +             locationIsValidForWildcard )
Here too. I would prefer the original.

2022-09-13 00:02 UTC, AniruddhaKanhere approved these changes

2022-09-16 22:33 UTC, alfred2g approved these changes

2022-09-16 22:41 UTC, merged