Replace magic numbers with macros and add explaining comments
FreeRTOS/coreMQTT pull request #249
Opened 2023-04-04 23:26 UTC by AniruddhaKanhere

Description
-----------
This PR removes the magic numbers from the code and replaces them with macros.
The value to which the macro is set is explained with comments in Doxygen formatting.

Test Steps
-----------

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-05 17:58 UTC, kstribrnAmzn submitted a review, later dismissed

2023-04-05 17:58 UTC, kstribrnAmzn commented
I've approved. I'll take it you're using the build checks for your testing?

2023-04-05 18:32 UTC, paulbartell commented on source/core_mqtt.c
>      MQTTFixedBuffer_t localBuffer;
```suggestion
    uint8_t pingreqPacket[ MQTT_PACKET_PINGREQ_SIZE ];
```

2023-04-05 18:32 UTC, paulbartell commented on source/core_mqtt.c
Line above isnt necessary.

2023-04-05 18:33 UTC, paulbartell commented on source/core_mqtt.c
> +            assert( packetSize == localBuffer.size );
```suggestion
```

2023-04-05 18:33 UTC, paulbartell commented on source/core_mqtt.c
> +                                 packetSize );
```suggestion
                                 MQTT_PACKET_PINGREQ_SIZE );
```

2023-04-05 18:33 UTC, paulbartell commented on source/core_mqtt.c
> +    uint8_t mqttHeader[ CORE_MQTT_PUBLISH_PACKET_HEADER_MAX_LENGTH ];
IMO, this doesn't really help readability.

2023-04-05 18:36 UTC, paulbartell commented on source/core_mqtt.c
> -    uint8_t serializedTopicFieldLength[ MQTT_SUB_UNSUB_MAX_VECTORS ][ 2 ];
Seems like a 16-bit length type would be a simpler way to handle this?

2023-04-05 18:44 UTC, paulbartell commented on source/core_mqtt.c
> -static size_t addEncodedStringToVector( uint8_t serailizedLength[ 2 ],
A typedef seems like a better choice here.

2023-04-05 18:45 UTC, paulbartell commented on source/core_mqtt.c
> +    serializedLength[ 0 ] = ( ( uint8_t ) ( ( length ) >> 8 ) );
A macro or static inline helper function would improve clarity here

2023-04-05 18:49 UTC, paulbartell commented on source/core_mqtt.c
> +#define CORE_MQTT_PUBLISH_PACKET_MAX_VECTORS              ( 4U )
CORE_MQTT_PUBLISH_PACKET_MAX_VECTORS is used in only one place. Moving this comment down there could improve clarity.

2023-04-05 18:49 UTC, paulbartell commented on source/core_mqtt.c
> +#define CORE_MQTT_CONNECT_PACKET_MAX_VECTORS              ( 11U )
Similar situation here. This is only used once.

2023-04-05 18:49 UTC, paulbartell commented on source/core_mqtt.c
> +#define CORE_MQTT_PUBLISH_PACKET_HEADER_MAX_LENGTH        ( 7U )
Same deal here.

2023-04-05 18:50 UTC, paulbartell requested changes
The additional comments are certainly useful. I don't think they warrant macros though, especially when used in a single place.

2023-04-06 18:02 UTC, paulbartell approved these changes

2023-04-06 20:11 UTC, kstribrnAmzn approved these changes

2023-04-06 20:11 UTC, merged