Add manifest file for coreMQTT
FreeRTOS/coreMQTT pull request #51
Opened 2020-09-11 20:45 UTC by abhidixi11

Add manifest file for coreMQTT

2020-09-11 20:54 UTC, aggarw13 submitted a review, later dismissed

2020-09-12 00:59 UTC, jainamt commented on manifest.yml
> + - name: "CMock"
hmm CMock seems odd. A customer using this library in production wont need CMock. Its only for unit testing

2020-09-15 16:38 UTC, luciodj requested changes
For consistency we need to use the "v1.0.0" format as for the others...

2020-09-15 16:55 UTC, luciodj approved these changes

2020-09-15 17:15 UTC, aggarw13 commented on manifest.yml
> +  "Client implementation of the MQTT 3.1.1 specification for embedded devices.\n"
The [coreJSON repo](https://github.com/FreeRTOS/coreJSON) uses the "suitable for microcontrollers" phrase. Should the "About" text and this manifest description of this repository be also consistent with it?
```suggestion
  "Client implementation of the MQTT 3.1.1 specification for embedded devices.\n"
```

2020-09-15 18:03 UTC, aggarw13 approved these changes

2020-09-15 19:43 UTC, jainamt approved these changes

2020-09-15 19:48 UTC, merged