Update MQTT 3.1.1 compliance text in doxygen and change log
FreeRTOS/coreMQTT pull request #57
Opened 2020-09-12 20:08 UTC by aggarw13

Update wording about MQTT library's compliance of the MQTT 3.1.1 specification in doxygen and CHANGELOG files﻿

2020-09-12 22:40 UTC, abhidixi11 approved these changes

2020-09-14 20:32 UTC, gkwicker requested changes
See comments

2020-09-14 20:32 UTC, gkwicker commented on CHANGELOG.md
> +The MQTT library is a client-side implementation of the [MQTT 3.1.1 specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349213), suitable for resource-constrained
Eliminate the `#_Toc385...` at the end of the URL, this directs the user to deep within the page.

2020-09-14 20:32 UTC, gkwicker commented on docs/doxygen/pages.txt
> +This MQTT client library provides an implementation of the [MQTT 3.1.1 specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349213). It is optimized for resource c
Eliminate the `#_Toc385...` at the end of the URL, this directs the user to deep within the page.

2020-09-14 20:58 UTC, yourslab commented on docs/doxygen/pages.txt
>  @page mqtt_design Design
This file is now `pages.dox`

2020-09-14 21:32 UTC, yourslab approved these changes

2020-09-14 22:40 UTC, gkwicker approved these changes

2020-09-14 22:40 UTC, merged